services:
  API:
    image: node:lts-alpine3.20
    command: sh -c "npm i && npm run dev"
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3001:3001
  DB:
    image: arm64v8/mysql:8.0-oracle
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456